// Every string the person reads lives here, never inside logic. One key per area.
export const t = {
  common: {
    appName: "MaydayMama",
    skipLink: "Przejdź do treści",
    loading: "Wczytywanie…",
    failedTitle: "Coś poszło nie tak",
    failed: "Nie udało się wczytać danych. Spróbuj ponownie.",
    actionFailed: "Nie udało się. Spróbuj ponownie za chwilę.",
    retry: "Spróbuj ponownie",
    backHome: "Wróć na start",
    cancel: "Anuluj",
    close: "Zamknij",
    roles: {
      woman: "Mama",
      partner: "Partner",
      supporter: "Bliska osoba",
    },
  },

  nav: {
    label: "Nawigacja",
    start: "Start",
    checkIn: "Mój dzień",
    questions: "Pytania",
    tasks: "Zadania",
    group: "Grupa",
    education: "Wiedza",
    help: "Pomoc",
    login: "Zaloguj się",
    signOut: "Wyloguj",
  },

  theme: {
    dark: "Ciemny motyw",
  },

  shell: {
    notFoundTitle: "Nie ma takiej strony",
    notFoundText: "Ten adres nigdzie nie prowadzi. Może link był niepełny.",
    notFoundBack: "Wróć na początek",
    notAllowedTitle: "To miejsce jest dla kogoś innego",
    notAllowed: {
      motherOnly: "To miejsce należy do mamy. Tylko ona widzi tu swoje wpisy.",
      lovedOnly: "Te pytania są dla bliskich osób mamy. Ty masz swoje miejsce na start.",
      noGroup: "To miejsce otworzy się, gdy dołączysz do grupy albo ją założysz.",
      pending: "Grupa zacznie działać, gdy mama przyjmie zaproszenie. Do tego czasu to miejsce jest puste.",
      closed: "Ta grupa została zamknięta, więc to miejsce nie przyjmuje już nowych odpowiedzi.",
    },
  },

  help: {
    title: "Pomoc",
    lead: "Jeśli jest Ci trudno, nie musisz czekać. Tu są miejsca, do których możesz zadzwonić.",
    linesTitle: "Telefony wsparcia",
    pathTitle: "Co możesz zrobić krok po kroku",
    regionalTitle: "Pomoc w Twoim województwie",
    regionalLink: "Strona instytucji",
    sourceLink: (name) => `Źródło: ${name}`,
    emergency: {
      name: "Numer alarmowy",
      number: "112",
      hours: "całą dobę",
      description: "Gdy ktoś jest w bezpośrednim niebezpieczeństwie. Zadzwoń od razu.",
    },
    signedOutTitle: "Gdy ktoś jest w niebezpieczeństwie",
    signedOutText:
      "Po zalogowaniu zobaczysz więcej telefonów wsparcia i spokojną ścieżkę pomocy. Numer alarmowy działa zawsze.",
    signedOutLink: "Zaloguj się",
    failedTitle: "Nie udało się wczytać wszystkich kontaktów",
    failedText: "Numer alarmowy jest zawsze pod ręką. Pozostałe kontakty spróbujemy wczytać jeszcze raz.",
    notADoctorTitle: "MaydayMama nie zastępuje lekarza",
    notADoctor:
      "Aplikacja niczego nie diagnozuje i nie daje porad medycznych. Pomaga zauważyć zmiany i podzielić się codziennymi obowiązkami.",
    talkTitle: "Nie musisz zostawać z tym w pojedynkę",
    talk: "Jeśli coś Cię niepokoi, porozmawiaj z kimś, komu ufasz: z bliską osobą, położną albo lekarzem.",
  },

  education: {
    title: "Wiedza o depresji poporodowej",
    lead: "Krótko i spokojnie: co warto wiedzieć, jak zauważyć trudne chwile i jak wspierać.",
    note: "To ogólne informacje, nie diagnoza. Tylko lekarz albo psycholog może ocenić, co się z kimś dzieje.",
    sections: [
      {
        id: "what",
        title: "Czym jest depresja poporodowa",
        icon: "heart",
        paragraphs: [
          "Depresja poporodowa to zaburzenie nastroju, które może pojawić się po narodzinach dziecka. Najczęściej w pierwszych miesiącach, ale bywa, że później. Dotyka wielu mam. Nie jest niczyją winą ani słabością.",
          "Można ją leczyć. Im wcześniej pojawi się wsparcie, tym łatwiej wrócić do równowagi.",
        ],
      },
      {
        id: "blues",
        title: "Baby blues a depresja poporodowa",
        icon: "cloud",
        paragraphs: [
          "Baby blues to chwilowe wahania nastroju, płaczliwość i zmęczenie w pierwszych dniach po porodzie. Zwykle mija samo w ciągu około dwóch tygodni.",
          "Gdy smutek, lęk albo pustka trwają dłużej, są silniejsze albo utrudniają codzienne życie, warto porozmawiać z lekarzem lub położną.",
        ],
      },
      {
        id: "signs",
        title: "Co warto zauważyć",
        icon: "leaf",
        paragraphs: ["Te sygnały mogą pojawić się u mamy. Każdy z nich osobno bywa zwyczajny. Niepokojące jest to, gdy jest ich kilka i trwają."],
        items: [
          "smutek, pustka albo płaczliwość przez większość dni",
          "brak radości z rzeczy, które zwykle cieszyły",
          "silny lęk, napięcie albo ciągłe martwienie się o dziecko",
          "kłopoty ze snem nawet wtedy, gdy dziecko śpi",
          "zmęczenie większe niż zwykłe zmęczenie po porodzie",
          "poczucie winy albo przekonanie, że jest się złą mamą",
          "wycofanie się z kontaktu z bliskimi",
          "myśli, że lepiej byłoby zniknąć, albo myśli o zrobieniu sobie krzywdy: wtedy od razu szukaj pomocy",
        ],
      },
      {
        id: "support",
        title: "Jak może wspierać bliska osoba",
        icon: "people",
        items: [
          "Zapytaj wprost i spokojnie, jak się naprawdę czuje.",
          "Słuchaj bez oceniania i bez rad na siłę.",
          "Weź na siebie konkretne sprawy: zakupy, obiad, spacer z dzieckiem, nocną zmianę.",
          "Zadbaj o to, żeby miała czas na sen i odpoczynek.",
          "Zachęć do rozmowy z lekarzem lub położną i, jeśli chce, pójdź razem z nią.",
          "Pamiętaj o sobie: bliska osoba też potrzebuje odpoczynku.",
        ],
      },
      {
        id: "help",
        title: "Kiedy i gdzie szukać pomocy",
        icon: "lifebuoy",
        paragraphs: [
          "Porozmawiaj z położną, lekarzem rodzinnym albo ginekologiem, jeśli trudne chwile trwają dłużej niż dwa tygodnie albo narastają.",
          "Gdy pojawiają się myśli o zrobieniu sobie krzywdy albo dziecku, nie czekaj: zadzwoń pod 112 albo zgłoś się na szpitalny oddział ratunkowy.",
        ],
      },
    ],
    helpLink: "Zobacz telefony wsparcia i ścieżkę pomocy",
  },

  landing: {
    brand: "MaydayMama",
    heroTitleLines: ["zauważyć wcześnie,", "wspierać razem"],
    heroScript: "mama nie musi radzić sobie sama",
    heroLead:
      "Aplikacja dla mamy i jej bliskich. Pomaga zauważyć trudne chwile po porodzie i podzielić się codziennymi obowiązkami.",
    signUp: "Załóż konto",
    signIn: "Zaloguj się",
    voicesTitle: "Ona mówi:",
    voices: ["„Dam radę.”", "„To tylko zmęczenie.”", "„Powinnam być szczęśliwa.”"],
    signalsTitle: "Bliscy widzą:",
    signals: [
      "nie wychodzi z domu",
      "częściej płacze",
      "je mniej, nie odpoczywa",
      "nie cieszą jej drobiazgi",
    ],
    voicesNote:
      "Brakuje bezpiecznego sposobu, żeby zauważyć to razem: bez oceniania mamy i bez działania za jej plecami.",
    rolesTitle: "Dla kogo jest MaydayMama",
    roles: [
      {
        key: "woman",
        title: "Mama",
        icon: "heart",
        text: "Zaznaczasz w kilku kliknięciach, jak się czujesz. Widzisz swoje podsumowanie i sama decydujesz, kto jest w Twojej grupie.",
      },
      {
        key: "partner",
        title: "Partner",
        icon: "chat",
        text: "Odpowiadasz na krótkie pytania o codzienność mamy i bierzesz na siebie konkretne zadania.",
      },
      {
        key: "supporter",
        title: "Bliska osoba",
        icon: "people",
        text: "Pomagasz w codziennych sprawach i od czasu do czasu odpowiadasz na krótkie pytanie.",
      },
    ],
    stepsTitle: "Jak to działa",
    steps: [
      {
        title: "Mama zakłada grupę i zaprasza bliskich",
        text: "Sama decyduje, kto do niej należy.",
      },
      {
        title: "Mama zaznacza dzień, bliscy odpowiadają na pytania",
        text: "Samopoczucie, sen, niepokój. Bez ocen i bez liczb.",
      },
      {
        title: "Wszyscy widzą łagodny, ogólny obraz",
        text: "I wiedzą, co zrobić: pomoc, zadania, wsparcie.",
      },
    ],
    privacyTitle: "Kto co widzi?",
    privacyScript: "nic za jej plecami",
    privacyLead:
      "Pojedyncze wpisy widzi tylko mama. Bliscy widzą wyłącznie ogólny obraz, nigdy odpowiedzi jednej osoby.",
    privacyColumns: ["Mama", "Partner", "Bliscy"],
    privacyRows: [
      { label: "Jej codzienne wpisy", sees: [true, false, false] },
      { label: "Ogólny obraz", sees: [true, true, true] },
      { label: "Pojedyncze odpowiedzi", sees: [false, false, false] },
      { label: "Wspólne zadania", sees: [true, true, true] },
    ],
    yes: "widzi",
    no: "nie widzi",
    safetyTitle: "Siatka bezpieczeństwa",
    safetyScript: "gdy jest naprawdę trudno:",
    safetyItems: [
      "Aplikacja niczego nie diagnozuje i nie zastępuje lekarza.",
      "Gdy jest trudno, możesz od razu zadzwonić pod jeden z numerów obok.",
    ],
    safetyLines: [
      { number: "112", note: "całą dobę" },
      { number: "116 123", note: "kryzys emocjonalny" },
      { number: "800 70 2222", note: "całą dobę" },
    ],
    helpLink: "Zobacz, gdzie szukać pomocy",
    finalTitle: "Zacznij od jednego konta",
    finalText: "Założenie konta zajmuje chwilę. Grupę założysz albo dołączysz do niej z zaproszenia.",
    phoneAlt: "Podgląd ekranu aplikacji",
    phone: {
      greeting: "Cześć, Anna",
      cardTitle: "Jak się dziś czujesz?",
      cardText: "Zapisz to w minutę. Widzisz to tylko Ty.",
      summary: "Ogólny obraz",
      summaryText: "Nie musisz radzić sobie z tym sama.",
    },
  },

  startGeneral: {
    title: "Dla każdego",
    educationTitle: "Wiedza",
    educationLead: "Co to jest depresja poporodowa i jak ją zauważyć.",
    helpTitle: "Pomoc",
    helpLead: "Telefony wsparcia i kolejne kroki.",
  },

  mock: {
    notice: "Tryb demonstracyjny: widzisz przykładowe dane, nie prawdziwe.",
    region: "Tryb demonstracyjny",
    perspective: "Pokaż jako",
    perspectives: {
      woman: "Mama (Anna)",
      partner: "Partner (Piotr)",
      supporter: "Bliska osoba (Marta)",
      no_group: "Osoba bez grupy",
      pending: "Grupa czeka na mamę",
      both: "Mama i bliska osoba (Julia)",
    },
    signedOut: "Nikt (wylogowano)",
    other: "Konto założone w demo",
    reset: "Zacznij demo od nowa",
    loginHint: (email, password) => `W demo zaloguj się jako ${email}, hasło: ${password}.`,
    errors: {
      validation: "Popraw zaznaczone pola.",
      pickOne: "Wybierz jedną z odpowiedzi.",
      passwordShort: "Hasło musi mieć co najmniej 8 znaków.",
      nameMissing: "Wpisz, jak mamy się do Ciebie zwracać.",
      detailsLong: "Opis może mieć najwyżej 500 znaków.",
    },
  },

  summary: {
    title: "Ogólny obraz",
    trend: {
      stable: {
        woman: "Ostatnie dni wyglądają spokojnie. Tak trzymaj, w swoim tempie.",
        loved: "Ostatnie dni wyglądają u niej spokojnie.",
      },
      uncertain: {
        woman: "Na razie nie da się powiedzieć nic pewnego. Przyglądamy się temu z uwagą i spokojem.",
        loved: "Na razie nie da się powiedzieć nic pewnego. Przyglądamy się temu z uwagą i spokojem.",
      },
      needs_attention: {
        woman: "Wygląda na to, że ostatnio jest Ci trudniej. Nie musisz radzić sobie z tym sama.",
        loved: "Wygląda na to, że ostatnio jest jej trudniej. Warto być teraz blisko.",
      },
    },
    helpLink: "Zobacz, gdzie szukać wsparcia",
    reasonsTitle: "Skąd ten obraz",
    crisisTitle: "Gdzie szukać wsparcia",
    reminderTitle: "Na dziś",
    narrativeLabel: "Opis",
    generated: (when) => `Przygotowano ${when}`,
  },

  start: {
    greeting: (name) => `Cześć, ${name}`,
  },

  account: {
    loginTitle: "Zaloguj się",
    loginLead: "Dobrze, że jesteś. Zaloguj się, żeby zobaczyć swoją grupę.",
    registerTitle: "Załóż konto",
    registerLead: "To zajmie chwilę. Potem założysz grupę albo dołączysz do niej z zaproszenia.",
    email: "Adres e-mail",
    password: "Hasło",
    newPasswordHint: "Co najmniej 8 znaków.",
    name: "Jak mamy się do Ciebie zwracać?",
    nameHint: "Imię albo zdrobnienie. Zobaczą je osoby w Twojej grupie.",
    loginSubmit: "Zaloguj się",
    registerSubmit: "Załóż konto",
    toRegister: "Nie masz jeszcze konta?",
    toRegisterLink: "Załóż konto",
    toLogin: "Masz już konto?",
    toLoginLink: "Zaloguj się",
    forgotLink: "Nie pamiętasz hasła?",
    resendActivation: "Wyślij link aktywacyjny jeszcze raz",
    // Never says whether an account exists for the address.
    resendSent: "Jeśli adres jest poprawny i konto czeka na aktywację, wyślemy nowy link.",
    checkMailTitle: "Sprawdź skrzynkę",
    checkMailText:
      "Jeśli adres jest poprawny, dostaniesz wiadomość z linkiem do aktywacji konta. Link działa 3 dni.",
    activatedTitle: "Konto jest aktywne",
    activatedText: "Możesz się już zalogować.",
    linkGoneTitle: "Ten link już nie działa",
    forgotTitle: "Nowe hasło",
    forgotLead: "Podaj adres e-mail konta. Wyślemy link do ustawienia nowego hasła.",
    forgotSubmit: "Wyślij link",
    forgotSent:
      "Jeśli adres jest poprawny, dostaniesz wiadomość z linkiem do nowego hasła. Link działa godzinę.",
    resetTitle: "Ustaw nowe hasło",
    resetLead: "Wpisz nowe hasło. Potem zalogujesz się nim.",
    newPassword: "Nowe hasło",
    resetSubmit: "Zapisz nowe hasło",
    resetDoneTitle: "Hasło jest zmienione",
    resetDoneText: "Zaloguj się nowym hasłem.",
    askNewLink: "Poproś o nowy link",
    accountTitle: "Moje konto",
    accountLink: "Moje konto",
    accountLead: (email) => `Zalogowano jako ${email}.`,
    deleteTitle: "Usuń konto",
    deleteText:
      "Usuniemy Twoje konto, Twoje odpowiedzi i Twoje członkostwo w grupach. Tego nie da się cofnąć.",
    deleteButton: "Usuń konto",
    deleteDialogTitle: "Usunąć konto?",
    deleteDialogText: [
      "Usuniemy Twoje konto, Twoje odpowiedzi i Twoje członkostwo w grupach. Zadania, które wzięłaś albo wziąłeś, wrócą do wspólnej listy.",
      "Tego nie da się cofnąć.",
    ],
    deleteMotherWarning:
      "Jesteś mamą w swojej grupie, więc usuniemy też całą grupę razem z jej danymi: wpisami, zadaniami i zaproszeniami. Osoby z grupy stracą do niej dostęp.",
    deleteConfirm: "Usuń konto",
    changeTitle: "Zmień hasło",
    currentPassword: "Obecne hasło",
    changeSubmit: "Zmień hasło",
    changed: "Hasło jest zmienione.",
    demoMail: "Demo: otwórz link z wiadomości",
    errors: {
      emailMissing: "Wpisz adres e-mail.",
      passwordMissing: "Wpisz hasło.",
      passwordShort: "Hasło musi mieć co najmniej 8 znaków.",
      nameMissing: "Wpisz imię albo zdrobnienie.",
    },
  },
  group: {
    onboardingLead: "Zacznijmy od tego, co chcesz teraz zrobić.",
    startAsTitle: "Co chcesz zrobić?",
    addGroup: "Dodaj grupę",
    addGroupTitle: "Dodaj grupę",
    addGroupLead: "Możesz należeć do wielu grup. W każdej masz własną rolę.",
    closeDialog: "Zamknij okno",
    switcher: {
      label: "Grupa",
      own: "Twoja grupa",
      of: (name) => `Grupa: ${name}`,
      noMother: "Grupa czeka na mamę",
      option: (name, role) => `${name} · ${role}`,
    },
    asWaiting: "Poczekam na link od mamy",
    asWaitingText: "Mama zaprosi Cię z aplikacji. Nie zakładamy wtedy żadnej grupy.",
    waitForLinkTitle: "Poproś mamę o link",
    waitForLinkText:
      "Poproś mamę, żeby zaprosiła Cię z aplikacji i wysłała Ci link. Gdy go otworzysz, dołączysz do jej grupy. Żadna grupa nie została założona.",
    waitForLinkMore: "Do tego czasu możesz przeczytać, jak rozpoznać trudne chwile, i zobaczyć, gdzie szukać pomocy.",
    asMother: "Jestem mamą",
    asMotherText: "Założysz grupę i zaprosisz do niej Partnera, a potem innych bliskich.",
    asPartner: "Jestem Partnerem",
    asPartnerText:
      "Założysz grupę i zaprosisz mamę. Grupa zacznie działać dopiero wtedy, gdy ona przyjmie zaproszenie.",
    joinTitle: "Masz zaproszenie?",
    joinText:
      "Otwórz link, który dostałaś albo dostałeś od bliskiej osoby. Zaprowadzi Cię prosto do grupy.",
    waitingTitle: "Czekamy na mamę",
    waitingLead: "Grupa zacznie działać, gdy mama przyjmie zaproszenie.",
    waitingText:
      "Do tego czasu nie ma tu podsumowań, pytań ani zadań. Mama decyduje, czy grupa ruszy i kto do niej należy.",
    inviteMotherTitle: "Zaproś mamę",
    inviteMotherText: "Utwórz link i wyślij go mamie w wiadomości, której używacie na co dzień.",
    inviteTitle: "Zaproś bliską osobę",
    inviteAtOnceTitle: "Zaproś Partnera i bliskie osoby",
    inviteAtOnceText:
      "Twoja przestrzeń jest gotowa. Razem łatwiej zauważyć, kiedy potrzebujesz więcej wsparcia. Utwórz link i wyślij go w wiadomości, której używacie na co dzień.",
    whoLegend: "Kogo zapraszasz?",
    roleOptions: {
      partner: "Partnera",
      supporter: "Bliską osobę z rodziny albo przyjaciół",
      woman: "Mamę",
    },
    email: "E-mail (nieobowiązkowo)",
    emailHint: "Jeśli go podasz, wyślemy tam link. Możesz też po prostu skopiować link.",
    createLink: "Utwórz link zaproszenia",
    linkLabel: "Link zaproszenia",
    copy: "Kopiuj link",
    copied: "Skopiowano link.",
    copyFailed: "Nie udało się skopiować. Zaznacz link i skopiuj go ręcznie.",
    expires: (when) => `Link jest ważny do ${when}.`,
    title: "Twoja grupa",
    lovedTitle: "Grupa",
    activeLead: "Osoby, które wspierają się nawzajem wokół mamy.",
    membersTitle: "Osoby w grupie",
    you: "to Ty",
    joined: (when) => `W grupie od ${when}`,
    remove: (name) => `Usuń: ${name}`,
    removeTitle: (name) => `Usunąć z grupy: ${name}?`,
    removeText:
      "Ta osoba nie zobaczy już podsumowania ani zadań grupy. Możesz zaprosić ją ponownie później.",
    removeConfirm: "Usuń z grupy",
    removed: (name) => `${name} nie należy już do grupy.`,
    closeTitle: "Zamknij grupę",
    closeText:
      "Gdy grupa przestanie być potrzebna, możesz ją zamknąć. Nikt nie doda już wpisów, odpowiedzi ani zadań.",
    closeButton: "Zamknij grupę",
    closeDialogTitle: "Zamknąć grupę?",
    closeDialogText: [
      "Po zamknięciu nikt nie doda już wpisów, odpowiedzi ani zadań i nie da się nikogo zaprosić.",
      "To, co już jest, zostanie widoczne. Tego nie da się cofnąć.",
    ],
    closedTitle: "Grupa jest zamknięta",
    closedText: "Nie można już do niej zapraszać ani dodawać zadań. To, co było, zostaje widoczne.",
    pendingNote: "Grupa czeka, aż mama przyjmie zaproszenie.",
    issuedTitle: "Wysłane zaproszenia",
    issuedEmpty: "Żadne zaproszenie nie czeka na przyjęcie.",
    issuedExpires: (when) => `Ważne do ${when}`,
    revoke: (role) => `Cofnij zaproszenie: ${role}`,
    revoked: "Zaproszenie zostało cofnięte.",
    leaveTitle: "Opuść grupę",
    leaveText: "Przestaniesz widzieć tę grupę. Twoje inne grupy zostają bez zmian.",
    leaveButton: "Opuść grupę",
    leaveDialogTitle: "Opuścić grupę?",
    leaveDialogText: [
      "Twoje odpowiedzi w tej grupie zostaną usunięte, a zadania, które wzięłaś albo wziąłeś, wrócą do wspólnej listy.",
      "Możesz do niej wrócić tylko z nowym zaproszeniem.",
    ],
    leaveConfirm: "Opuść grupę",
    deleteClosedTitle: "Usuń zamkniętą grupę",
    deleteClosedText:
      "Możesz ją usunąć razem z jej danymi, a potem założyć nową.",
    deleteClosedButton: "Usuń grupę",
    deleteClosedDialogTitle: "Usunąć grupę?",
    deleteClosedDialogText: [
      "Zniknie cała grupa: osoby, zadania i odpowiedzi. Tego nie da się cofnąć.",
    ],
    invitationTitle: (name) => `${name} zaprasza Cię do grupy`,
    invitationLead: "MaydayMama pomaga bliskim zauważyć, kiedy mama potrzebuje wsparcia, i dzielić się codziennymi obowiązkami.",
    invitationRole: "Twoja rola w grupie",
    invitationClosed: "Ta grupa została już zamknięta, więc nie można do niej dołączyć.",
    accept: "Przyjmij zaproszenie",
    signInToAccept: "Żeby przyjąć zaproszenie, zaloguj się albo załóż konto. Potem wrócisz tutaj.",
    signIn: "Zaloguj się",
    signUp: "Załóż konto",
    goneTitle: "Ten link już nie działa",
    goneText:
      "Zaproszenie mogło wygasnąć albo zostało już użyte. Poproś osobę, która Cię zaprosiła, o nowy link.",
    roleDescriptions: {
      woman: "Zobaczysz swoje podsumowanie i zadania bliskich. Ty decydujesz, kto należy do grupy.",
      partner: "Odpowiesz na krótkie pytania o codzienność mamy i podzielisz się zadaniami.",
      supporter: "Pomożesz w codziennych sprawach i od czasu do czasu odpowiesz na krótkie pytania.",
    },
  },
  wellbeing: {
    title: "Mój dzień",
    lead: "Kilka kliknięć, bez ocen i bez liczb. Zaznacz to, co jest najbliżej prawdy.",
    privacy:
      "Te wpisy widzisz tylko Ty. Bliscy nigdy nie zobaczą pojedynczego wpisu, najwyżej ogólny obraz.",
    mood: {
      legend: "Jak się dziś czujesz?",
      label: "Samopoczucie",
      options: {
        good: "Dobrze",
        okay: "W porządku",
        low: "Raczej słabo",
        very_low: "Bardzo ciężko",
      },
    },
    sleep: {
      legend: "Jak Ci się spało?",
      label: "Sen",
      options: { enough: "Wystarczająco", little: "Mało", almost_none: "Prawie wcale" },
    },
    anxiety: {
      legend: "Czy coś Cię dziś niepokoi?",
      label: "Niepokój",
      options: { none: "Raczej nie", some: "Trochę", strong: "Bardzo" },
    },
    pickOne: "Wybierz jedną z odpowiedzi.",
    save: "Zapisz wpis",
    saved: "Dziękujemy, że się zatrzymałaś. Wpis jest zapisany.",
    closed: "Grupa jest zamknięta, więc nie dodasz już nowych wpisów. Twoje wpisy zostają tutaj.",
    historyTitle: "Moje wpisy",
    historyEmpty: "Nie masz jeszcze wpisów. Pierwszy zajmie mniej niż minutę.",
    ctaTitle: "Jak się dziś czujesz?",
    ctaLead: "Zapisz to w minutę. Widzisz to tylko Ty.",
    selfCareTitle: "Chwila dla siebie",
    minutes: (n) => `${n} min`,
    tasksTitle: "Otwarte zadania bliskich",
    tasksEmpty: "Nie ma teraz otwartych zadań.",
    allTasks: "Wszystkie zadania",
  },
  observations: {
    title: "Jak ona się ma?",
    lead: "Kilka krótkich pytań o jej codzienność. Odpowiedz tylko na te, na które znasz odpowiedź.",
    privacy:
      "Twoich odpowiedzi nikt nie zobaczy pojedynczo ani z Twoim imieniem. Trafiają tylko do ogólnego obrazu.",
    send: "Wyślij odpowiedzi",
    atLeastOne: "Odpowiedz na co najmniej jedno pytanie.",
    thanksTitle: "Dziękujemy",
    thanksText:
      "Twoje odpowiedzi pomogą zauważyć, jak zmienia się jej codzienność. Nikt nie zobaczy ich pojedynczo.",
    toTasks: "Zobacz zadania",
    ctaTitle: "Jak ona się ma?",
    ctaLead: "Odpowiedz na kilka krótkich pytań. To zajmie minutę.",
    tasksTitle: "Otwarte zadania",
    tasksEmpty: "Nie ma teraz otwartych zadań. Możesz dodać nowe.",
  },

  tasks: {
    title: "Zadania",
    lead: "Wspólne, codzienne sprawy. Weź to, z czym możesz pomóc.",
    addTitle: "Dodaj zadanie",
    taskTitle: "Co trzeba zrobić?",
    taskTitleHint: "Krótko, najwyżej 120 znaków.",
    details: "Szczegóły (nieobowiązkowo)",
    detailsHint: "Najwyżej 500 znaków.",
    add: "Dodaj zadanie",
    added: "Dodano zadanie.",
    titleMissing: "Wpisz krótki tytuł zadania.",
    titleLong: "Tytuł może mieć najwyżej 120 znaków.",
    detailsLong: "Szczegóły mogą mieć najwyżej 500 znaków.",
    open: "Do wzięcia",
    claimed: "W toku",
    done: "Zrobione",
    noneHere: "Nic tu teraz nie ma.",
    empty: "Nie ma jeszcze zadań. Dodaj pierwsze, na przykład zakupy albo obiad.",
    addedBy: (name) => `Dodane przez: ${name}`,
    takenBy: (name) => `Zajmuje się: ${name}`,
    doneBy: (name) => `Zrobione przez: ${name}`,
    you: "Ty",
    take: "Biorę to",
    finish: "Oznacz jako zrobione",
    release: "Oddaj zadanie",
    closed: "Grupa jest zamknięta, więc nie można dodawać ani brać zadań. Lista zostaje do wglądu.",
    ideasTitle: "Pomysły na zadania",
    ideasLead: "Gotowe propozycje. Dodaj te, które pasują.",
    ideaAdd: "Dodaj",
    ideaAddLabel: (title) => `Dodaj: ${title}`,
    ideaAdded: (title) => `Dodano zadanie: ${title}.`,
  },
};

// A one-letter word must not end a line, so it is glued to the word after it (a no-break space).
// Used for the landing page, where long lines of prose are set in wide columns.
const glue = (value) => {
  if (typeof value === "string") return value.replace(/(?<=^|[\s(„])([aiouwzAIOUWZ])\s+/g, "$1\u00a0");
  if (Array.isArray(value)) return value.map(glue);
  if (value && typeof value === "object") {
    return Object.fromEntries(Object.entries(value).map(([key, item]) => [key, glue(item)]));
  }
  return value;
};
t.landing = glue(t.landing);
