# Generated by Django 6.1.1 on 2026-10-03 20:56

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models

import core.clock
import core.models.user


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(blank=True, null=True, verbose_name="last login"),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("display_name", models.CharField(max_length=60)),
                ("is_active", models.BooleanField(default=True)),
                ("voivodeship", models.CharField(blank=True, default="", max_length=30)),
                ("email_reminders", models.BooleanField(default=True)),
                ("date_joined", models.DateTimeField(default=core.clock.now)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        django.db.models.functions.text.Lower("email"), name="user_email_unique_ci"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("voivodeship", ""),
                            (
                                "voivodeship__in",
                                (
                                    "dolnoslaskie",
                                    "kujawsko_pomorskie",
                                    "lodzkie",
                                    "lubelskie",
                                    "lubuskie",
                                    "malopolskie",
                                    "mazowieckie",
                                    "opolskie",
                                    "podkarpackie",
                                    "podlaskie",
                                    "pomorskie",
                                    "slaskie",
                                    "swietokrzyskie",
                                    "warminsko_mazurskie",
                                    "wielkopolskie",
                                    "zachodniopomorskie",
                                ),
                            ),
                            _connector="OR",
                        ),
                        name="user_voivodeship_known",
                    ),
                ],
            },
            managers=[
                ("objects", core.models.user.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("status", models.CharField(max_length=10)),
                ("created_at", models.DateTimeField(default=core.clock.now)),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("status__in", ("pending", "active", "closed"))),
                        name="group_status_known",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Invitation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("token", models.CharField(max_length=64, unique=True)),
                ("role", models.CharField(max_length=10)),
                ("created_at", models.DateTimeField(default=core.clock.now)),
                ("expires_at", models.DateTimeField()),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invitations",
                        to="core.group",
                    ),
                ),
                (
                    "invited_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invitations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MailLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("kind", models.CharField(max_length=30)),
                ("key_hash", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(default=core.clock.now)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["kind", "key_hash", "created_at"],
                        name="core_maillo_kind_273cf5_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Membership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("role", models.CharField(max_length=10)),
                ("joined_at", models.DateTimeField(default=core.clock.now)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="core.group",
                    ),
                ),
                (
                    "invitation",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="membership",
                        to="core.invitation",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="membership",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CheckIn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("mood", models.CharField(max_length=10)),
                ("sleep", models.CharField(max_length=12)),
                ("anxiety", models.CharField(max_length=10)),
                ("created_at", models.DateTimeField(default=core.clock.now)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="check_ins",
                        to="core.group",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="check_ins",
                        to="core.membership",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Observation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(default=core.clock.now)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="observations",
                        to="core.membership",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="observations",
                        to="core.group",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ObservationAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("question_id", models.CharField(max_length=40)),
                ("value", models.CharField(max_length=20)),
                (
                    "observation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="core.observation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReminderLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("kind", models.CharField(max_length=20)),
                ("day", models.DateField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reminder_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=120)),
                ("details", models.CharField(blank=True, default="", max_length=500)),
                ("status", models.CharField(default="open", max_length=10)),
                ("created_at", models.DateTimeField(default=core.clock.now)),
                ("claimed_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "claimed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="claimed_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="core.group",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="invitation",
            constraint=models.CheckConstraint(
                condition=models.Q(("role__in", ("woman", "partner", "supporter"))),
                name="invitation_role_known",
            ),
        ),
        migrations.AddConstraint(
            model_name="invitation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("used_at__isnull", True), ("revoked_at__isnull", True), _connector="OR"
                ),
                name="invitation_not_used_and_revoked",
            ),
        ),
        migrations.AddConstraint(
            model_name="membership",
            constraint=models.CheckConstraint(
                condition=models.Q(("role__in", ("woman", "partner", "supporter"))),
                name="membership_role_known",
            ),
        ),
        migrations.AddConstraint(
            model_name="membership",
            constraint=models.UniqueConstraint(
                condition=models.Q(("role", "woman")),
                fields=("group",),
                name="membership_one_woman_per_group",
            ),
        ),
        migrations.AddIndex(
            model_name="checkin",
            index=models.Index(
                fields=["group", "created_at"], name="core_checki_group_i_0cbbf0_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="checkin",
            constraint=models.CheckConstraint(
                condition=models.Q(("mood__in", ("good", "okay", "low", "very_low"))),
                name="check_in_mood_known",
            ),
        ),
        migrations.AddConstraint(
            model_name="checkin",
            constraint=models.CheckConstraint(
                condition=models.Q(("sleep__in", ("enough", "little", "almost_none"))),
                name="check_in_sleep_known",
            ),
        ),
        migrations.AddConstraint(
            model_name="checkin",
            constraint=models.CheckConstraint(
                condition=models.Q(("anxiety__in", ("none", "some", "strong"))),
                name="check_in_anxiety_known",
            ),
        ),
        migrations.AddIndex(
            model_name="observation",
            index=models.Index(
                fields=["group", "created_at"], name="core_observ_group_i_6d2b59_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="observationanswer",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "value__in",
                        ("yes", "no", "unsure", "more_than_usual", "as_usual", "less_than_usual"),
                    )
                ),
                name="answer_value_known",
            ),
        ),
        migrations.AddConstraint(
            model_name="observationanswer",
            constraint=models.UniqueConstraint(
                fields=("observation", "question_id"), name="answer_one_per_question"
            ),
        ),
        migrations.AddConstraint(
            model_name="reminderlog",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("kind__in", ("check_in_due", "observation_due", "task_in_progress"))
                ),
                name="reminder_kind_known",
            ),
        ),
        migrations.AddConstraint(
            model_name="reminderlog",
            constraint=models.UniqueConstraint(
                fields=("user", "kind", "day"), name="reminder_once_per_day"
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(fields=["group", "status"], name="core_task_group_i_980b15_idx"),
        ),
        migrations.AddConstraint(
            model_name="task",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ("open", "claimed", "done"))),
                name="task_status_known",
            ),
        ),
        migrations.AddConstraint(
            model_name="task",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("claimed_by__isnull", True),
                        ("completed_at__isnull", True),
                        ("status", "open"),
                    ),
                    models.Q(
                        ("claimed_by__isnull", False),
                        ("completed_at__isnull", True),
                        ("status", "claimed"),
                    ),
                    models.Q(
                        ("claimed_by__isnull", False),
                        ("completed_at__isnull", False),
                        ("status", "done"),
                    ),
                    _connector="OR",
                ),
                name="task_status_matches_claim",
            ),
        ),
    ]
